# Generated by Django 6.0.4 on 2026-06-05 19:41

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import netbox_cisco_aci.validators
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
        ('netbox_cisco_aci', '0009_static_routes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACIBFDInterfacePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=64, validators=[netbox_cisco_aci.validators.aci_policy_name_validator])),
                ('name_alias', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('admin_state', models.CharField(default='enabled', max_length=16)),
                ('detection_multiplier', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('min_rx_interval_ms', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(999)])),
                ('min_tx_interval_ms', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(999)])),
                ('echo_admin_state', models.CharField(default='enabled', max_length=16)),
                ('echo_rx_interval_ms', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(999)])),
                ('slow_timer_ms', models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(10000)])),
                ('controls', models.JSONField(blank=True, default=list)),
                ('aci_tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bfd_interface_policies', to='netbox_cisco_aci.acitenant')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'ACI BFD Interface Policy',
                'verbose_name_plural': 'ACI BFD Interface Policies',
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ACIBFDInterfaceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=64, validators=[netbox_cisco_aci.validators.aci_policy_name_validator])),
                ('name_alias', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('aci_logical_interface_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bfd_attachment', to='netbox_cisco_aci.acilogicalinterfaceprofile')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('aci_bfd_interface_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='netbox_cisco_aci.acibfdinterfacepolicy')),
            ],
            options={
                'verbose_name': 'ACI BFD Interface Attachment',
                'verbose_name_plural': 'ACI BFD Interface Attachments',
                'ordering': ('aci_logical_interface_profile',),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='acibfdinterfacepolicy',
            constraint=models.UniqueConstraint(fields=('aci_tenant', 'name'), name='netbox_cisco_aci_acibfdinterfacepolicy_tenant_name_unique'),
        ),
    ]
