# Generated by Django 6.0.4 on 2026-06-05 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
        ('ipam', '0001_squashed'),
        ('netbox_cisco_aci', '0010_bfd'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='acibridgedomainsubnet',
            name='netbox_cisco_aci_acibdsubnet_bd_gw_unique',
        ),
        migrations.AddField(
            model_name='acibridgedomainsubnet',
            name='gateway_ipam_ip_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ipam.ipaddress'),
        ),
        migrations.AlterField(
            model_name='acibridgedomainsubnet',
            name='gateway_ip',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='acibridgedomainsubnet',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_ip', ''), _negated=True), fields=('aci_bridge_domain', 'gateway_ip'), name='netbox_cisco_aci_acibdsubnet_bd_gw_unique'),
        ),
        migrations.AddConstraint(
            model_name='acibridgedomainsubnet',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_ipam_ip_address__isnull', False)), fields=('aci_bridge_domain', 'gateway_ipam_ip_address'), name='netbox_cisco_aci_acibdsubnet_bd_ipam_unique'),
        ),
    ]
