# Generated by Django 6.0.4 on 2026-06-06 18:50

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import netbox_cisco_aci.validators
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
        ('netbox_cisco_aci', '0012_pod_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='acipodpolicygroup',
            name='datetime_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='netbox_cisco_aci.acintppolicy'),
        ),
        migrations.CreateModel(
            name='ACIBGPRouteReflectorPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=64, validators=[netbox_cisco_aci.validators.aci_policy_name_validator])),
                ('name_alias', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('admin_state', models.CharField(default='enabled', max_length=16)),
                ('autonomous_system_number', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4294967295)])),
                ('aci_fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='netbox_cisco_aci.acifabric')),
                ('aci_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='netbox_cisco_aci.acitenant')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'ACI BGP Route Reflector Policy',
                'verbose_name_plural': 'ACI BGP Route Reflector Policies',
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ACIBGPRouteReflectorNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=64, validators=[netbox_cisco_aci.validators.aci_policy_name_validator])),
                ('name_alias', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('node_id', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4000)])),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('bgp_rr_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rr_nodes', to='netbox_cisco_aci.acibgproutereflectorpolicy')),
            ],
            options={
                'verbose_name': 'ACI BGP RR Node',
                'verbose_name_plural': 'ACI BGP RR Nodes',
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='acipodpolicygroup',
            name='bgp_rr_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='netbox_cisco_aci.acibgproutereflectorpolicy'),
        ),
        migrations.CreateModel(
            name='ACICOOPGroupPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=64, validators=[netbox_cisco_aci.validators.aci_policy_name_validator])),
                ('name_alias', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('admin_state', models.CharField(default='enabled', max_length=16)),
                ('authentication_type', models.CharField(default='strict', max_length=16)),
                ('aci_fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='netbox_cisco_aci.acifabric')),
                ('aci_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='netbox_cisco_aci.acitenant')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'ACI COOP Group Policy',
                'verbose_name_plural': 'ACI COOP Group Policies',
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='acipodpolicygroup',
            name='coop_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='netbox_cisco_aci.acicoopgrouppolicy'),
        ),
        migrations.CreateModel(
            name='ACIISISDomainPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=64, validators=[netbox_cisco_aci.validators.aci_policy_name_validator])),
                ('name_alias', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('admin_state', models.CharField(default='enabled', max_length=16)),
                ('metric_style', models.CharField(default='wide', max_length=8)),
                ('lsp_fast_flood_enabled', models.BooleanField(default=True)),
                ('lsp_gen_init_intvl_ms', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(120000)])),
                ('lsp_gen_max_intvl_ms', models.PositiveIntegerField(default=8000, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(120000)])),
                ('lsp_gen_sec_intvl_ms', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(120000)])),
                ('aci_fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='netbox_cisco_aci.acifabric')),
                ('aci_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='netbox_cisco_aci.acitenant')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'ACI IS-IS Domain Policy',
                'verbose_name_plural': 'ACI IS-IS Domain Policies',
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='acipodpolicygroup',
            name='isis_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='netbox_cisco_aci.aciisisdomainpolicy'),
        ),
        migrations.CreateModel(
            name='ACIPodProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=64, validators=[netbox_cisco_aci.validators.aci_policy_name_validator])),
                ('name_alias', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('aci_fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pod_profiles', to='netbox_cisco_aci.acifabric')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'ACI Pod Profile',
                'verbose_name_plural': 'ACI Pod Profiles',
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ACIPodSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=64, validators=[netbox_cisco_aci.validators.aci_policy_name_validator])),
                ('name_alias', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('selector_type', models.CharField(default='range', max_length=8)),
                ('pod_block_from', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(254)])),
                ('pod_block_to', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(254)])),
                ('pod_policy_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selectors', to='netbox_cisco_aci.acipodpolicygroup')),
                ('pod_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectors', to='netbox_cisco_aci.acipodprofile')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'ACI Pod Selector',
                'verbose_name_plural': 'ACI Pod Selectors',
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='acibgproutereflectorpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('aci_tenant__isnull', True)), fields=('aci_fabric', 'name'), name='netbox_cisco_aci_acibgprr_fabric_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='acibgproutereflectorpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('aci_tenant__isnull', False)), fields=('aci_fabric', 'aci_tenant', 'name'), name='netbox_cisco_aci_acibgprr_fabric_tenant_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='acibgproutereflectornode',
            constraint=models.UniqueConstraint(fields=('bgp_rr_policy', 'node_id'), name='netbox_cisco_aci_acibgprrnode_policy_nodeid_unique'),
        ),
        migrations.AddConstraint(
            model_name='acicoopgrouppolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('aci_tenant__isnull', True)), fields=('aci_fabric', 'name'), name='netbox_cisco_aci_acicoop_fabric_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='acicoopgrouppolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('aci_tenant__isnull', False)), fields=('aci_fabric', 'aci_tenant', 'name'), name='netbox_cisco_aci_acicoop_fabric_tenant_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='aciisisdomainpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('aci_tenant__isnull', True)), fields=('aci_fabric', 'name'), name='netbox_cisco_aci_aciisis_fabric_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='aciisisdomainpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('aci_tenant__isnull', False)), fields=('aci_fabric', 'aci_tenant', 'name'), name='netbox_cisco_aci_aciisis_fabric_tenant_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='acipodprofile',
            constraint=models.UniqueConstraint(fields=('aci_fabric', 'name'), name='netbox_cisco_aci_acipodprofile_fabric_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='acipodselector',
            constraint=models.UniqueConstraint(fields=('pod_profile', 'name'), name='netbox_cisco_aci_acipodselector_profile_name_unique'),
        ),
    ]
